"""empty message

Revision ID: 792bc16ae193
Revises: 600773643c2f
Create Date: 2018-10-02 16:35:57.112984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792bc16ae193'
down_revision = '600773643c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roles', sa.String(length=1024), server_default='[]', nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
