"""empty message

Revision ID: 7efea5878448
Revises: 645bbeaa2967
Create Date: 2018-10-03 21:37:29.159515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7efea5878448'
down_revision = '645bbeaa2967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('electorate', sa.String(length=1024), server_default='[]', nullable=False))
    op.drop_column('vote', 'electorate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('electorate', mysql.VARCHAR(length=1024), server_default=sa.text(u"'[]'"), nullable=False))
    op.drop_column('poll', 'electorate')
    # ### end Alembic commands ###
