"""empty message

Revision ID: cc06eab53685
Revises: d2ad273f37fa
Create Date: 2018-10-02 18:35:19.843822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc06eab53685'
down_revision = 'd2ad273f37fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('electorate', sa.String(length=1024), server_default='[]', nullable=False))
    op.drop_column('vote', 'roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('roles', mysql.VARCHAR(length=1024), server_default=sa.text(u"'[]'"), nullable=False))
    op.drop_column('vote', 'electorate')
    # ### end Alembic commands ###
